import { makeStyles } from '@material-ui/core/styles';

export default makeStyles((theme) => ({
  root: {
    '& label.Mui-focused': {
      color: ' #D0D5DD ',
    },
    '& .MuiInput-underline:after': {
      borderBottomColor: '#D0D5DD',
    },
    '& .MuiOutlinedInput-root': {
      '& fieldset': {
        borderColor: 'none',
        border: '1px solid #D0D5DD',
        boxShadow: '0px 1px 2px rgba(16, 24, 40, 0.05)',
        width: '368px',
        height: '44px',
        marginLeft: '0px',
        marginTop: '6px',
      },
      '&:hover fieldset': {
        borderColor: ' #D0D5DD ',
      },
      '&.Mui-focused fieldset': {
        borderColor: ' #D0D5DD ',
      },
    },
    '& .MuiOutlinedInput-input': {
      fontFamily: 'Nunito, sans-serif',
      fontStyle: 'normal',
      fontWeight: '300',
      fontSize: '16px',
    },
    height: '100vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    fontFamily: 'Montserrat, sans-serif',
  },

  element: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: '32px',
  },

  submit: {
    margin: theme.spacing(3, 0, 2),
    backgroundColor: '#DA0175',
    width: '160px',
    height: '33px',
    borderRadius: '10px',
    color: '#F8F8F9',
    '&:hover': {
      backgroundColor: '#0E8750',
    },
  },

  button: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    fontFamily: 'Nunito, sans-serif',
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: '18px',
    lineHeight: '25px',
    marginLeft:'40px',
  },
  buttonLink: {
    textDecoration: 'none',
  },
  cadastroLink: {
    color: '#DA0175',
    marginTop: '13px',
    marginLeft: '6px',
    marginTop: '-2px',
  },
  link: {
    display: 'flex',
    alignItems: 'center',
    fontFamily: 'Nunito',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: '14px',
    lineHeight: '20px',
    color: '#344054',
  },
  login: {
    color: '#DA0175',
  },
  spanErroCadastro: {
    color: '#ff0000',
    marginBottom: '10px',
  },
  cardLeft: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    width: '940px',
    height: '100%',
  },
  formulario:{
    width: '100%',
    height: '80%',
    marginTop: '32px',
  },
  status: {
    height: '100%',
    background: '#F0F0F5',
    fontSize: '1.5rem',
    display: 'flex',
  },
  Paper: {
    height: '100%',
  },
  txtForm: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    fontFamily: 'Nunito',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: '14px',
    lineHeight: '20px',
    color: '#344054',
    marginLeft: '-140px'
  },
  inputForm: {
    width: '368px',
    height: '44px',
    background: '#FFFFFF',
    border: '1px solid #D0D5DD',
    boxSizing: 'border-box',
    boxShadow: '0px 1px 2px rgba(16, 24, 40, 0.05)',
    borderRadius: '8px',
  },
  margin: {
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: '16px',
    lineHeight: '24px',
    marginTop: '6px',
    color: '#667085',
  },
  h1: {
    fontFamily: 'Montserrat, sans-serif',
    textAlign: 'center',
    fontStyle: 'normal',
    fontWeight: 'bold',
    fontSize: '24px',
    lineHeight: '130%',
    color: '#343447',
    marginLeft: '40px',
    marginTop: '20px',
    width: '100%',
  },
  titulo: {
    display: 'flex',
  },
  iconesStatus: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    width: '32px',
    height: '32px',
    marginTop: '180px',
    marginLeft: '50px',
    marginBottom: '14px',
  },
  traco: {
    width: '5px',
    border: '3px',
  },
  caracterStatus: {
    display: 'flex',
    flexDirection: 'column',
    marginTop: '81px',
    marginLeft: '25px',
  },
  tituloVerde: {
    fontFamily: 'Montserrat',
    fontStyle: 'normal',
    fontWeight: 'bold',
    fontSize: '18px',
    lineHeight: '130%',
    color: '#0E8750',
    marginBottom: '8px',
  },
  tituloCinza: {
    fontFamily: 'Nunito',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: '18px',
    lineHeight: '130%',
    color: '#3F3F55',
    marginBottom: '35px',
  },
  barraStatus: {
    with: '82px',
    height: '6px',
    display: 'flex',
    justifyContent: 'space-between',
    marginBotton: '50px',
    marginLeft: '50px',
  },
  layoutPrincipal: {
    display: 'flex',
  },
}));
